### ISSUE TITLE
TimeAndSale subscription receives double events

### ISSUE THREAD

**Issue by 10010111** [dxFeed/dxfeed-python-api#19]
<img width="1121" alt="Screenshot 2020-06-25 at 18 04 44" src="https://user-images.githubusercontent.com/65687613/85755580-5d3e2380-b70e-11ea-9100-51de9347b57e.png">

**Comment by alimantu** [comment]
Hi!
Thank you for informing us @10010111. Can you please add little bit more details? Saved snapshot of data could be quite useful for example.

Best regards, 
Aleksandr Salynskii

**Comment by 10010111** [comment]
Hello Aleksandr.

Sure. Every event seems to be recorded twice by the listener. I've attached the data frame (as of now) as a pickle object. After unpacking you may load it with:

import pickle
df = pickle.load(open('tns_sub_data.p', 'rb'))
df.shape[0] == 2*df.drop_duplicates().shape[0]

Unfortunately I was unable to pickle the entire tns_sub object since "self.listener,self.subscription,self.u_data cannot be converted to a Python object for pickling". Hope this helps though!

[tns_sub_data.p.zip](https://github.com/dxFeed/dxfeed-python-api/files/4832934/tns_sub_data.p.zip)

PS: Thanks for providing this repository!

**Comment by iamishalkin** [comment]
Hello, @10010111

Thank you for the details you've provided. Duplicated records differ in the Scope field. It is not implemented in the current 0.4.0 version, but it is already in EN-1454 Pull Request ([github.com/dxFeed/dxfeed-python-api/pull/18](https://github.com/dxFeed/dxfeed-python-api/pull/18)).

This field is responsible for the scope of the record. Its value can be 0 for the record in the scope of the whole market, 1 for the scope of a particular exchange. The order event type may have two more values: 2 for aggregated scope or BBO for a particular market maker and 3 for an individual order.

If you urgently need Scope functionality you can try dev version from PR
[dxfeed-0.4.1.tar.gz](https://github.com/dxFeed/dxfeed-python-api/files/4851438/dxfeed-0.4.1.tar.gz)

**Comment by 10010111** [comment]
Hello, iamishalkin.

Excellent - I'll give the dev version a try! Thank you for providing such a detailed answer.
