### ISSUE TITLE
Could not build wheels for dxfeed which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by asvechkar** [dxFeed/dxfeed-python-api#25]
CentOS 7, Python 3.8.5, pip 20.2

**Comment by asvechkar** [comment]
Change Python to 3.6.8. Same error.

**Comment by alimantu** [comment]
Hi @asvechkar,

Can you provide little bit more information, so we'll be able to reproduce the steps?

Also d'like to mention that we are using poetry and taskipy for project build, so to build the wheel + tar.gz you need to execute command `poetry run task build`, also if you've tried to build it previously I highly recommend you to run `poetry run task clear` before it. 

Please let us know did it help you or not.

P.S. Also you can check the `pyproject.toml`'s [tool.taskipy.tasks] section to see list of available commands and what do they mean.

**Comment by sretlawd** [comment]
Had the same issue.  The problem is that if you try to install directly via pip, it doesn't properly checkout the git submodules and the build.py script fails.  Here's a Dockerfile to reproduce (same result if just installing dxfeed==0.5.0 or the git master):

```
FROM python:3.8-slim
RUN apt-get update && apt-get install -y build-essential git
RUN pip install git+https://github.com/dxFeed/dxfeed-python-api.git@master
```

Resulting in:

```
Building wheels for collected packages: dxfeed
  Building wheel for dxfeed (PEP 517): started
  Building wheel for dxfeed (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp10sylzc2
       cwd: /tmp/pip-req-build-j0sljjv5
  Complete output (25 lines):
  A setup.py file already exists. Using it.
  Traceback (most recent call last):
    File "/tmp/pip-req-build-j0sljjv5/setup.py", line 1, in <module>
      from setuptools import setup
  ModuleNotFoundError: No module named 'setuptools'
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-51cb1m21/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 57, in build_wheel
      return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory)))
    File "/tmp/pip-build-env-51cb1m21/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 59, in make_in
      wb.build()
    File "/tmp/pip-build-env-51cb1m21/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 89, in build
      self._build(zip_file)
    File "/tmp/pip-build-env-51cb1m21/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 121, in _build
      self._run_build_command(setup)
    File "/tmp/pip-build-env-51cb1m21/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 149, in _run_build_command
      subprocess.check_call(
    File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/local/bin/python', '/tmp/pip-req-build-j0sljjv5/setup.py', 'build', '-b', '/tmp/pip-req-build-j0sljjv5/build']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dxfeed
Failed to build dxfeed
ERROR: Could not build wheels for dxfeed which use PEP 517 and cannot be installed directly
```

**Comment by cobujo** [comment]
Yup, I'm getting this same error trying to install dxfeed in a python:3.7 docker image.

What's weird is that this worked about a month ago, and I can't for the life of me figure out why and exactly what changed.

**Comment by sretlawd** [comment]
@cobujo , same here, now that you mention it I also had no problems until recently.  That gave me the idea to check poetry, and I see that they had a new minor version release recently (it's at 1.1.2 now) and that seems to be the culprit.  I froze poetry to v1.0.10 in sretlawd/dxfeed-python-api@cb1323d, and now the following Dockerfile works fine:

```
FROM python:3.8
RUN pip install git+https://github.com/sretlawd/dxfeed-python-api.git@poetry_version_freeze
```

How brittle ... I imagine it's possible specify >=0.12,<1.1 but I've already lost too much time to this issue, I'll let the dxFeed guys figure out a proper fix.  :-)

**Comment by cobujo** [comment]
@sretlawd YES! I thought the specific issue was with the standalone build backend which changes the `[build-system]` params in poetry 1.1.0, but after changing these I was still erroring out.  I froze the version like you did and I'm up and running.

Thanks for your comment, and yeah until the dxfeed team can take a good look at this I'm content with freezing poetry for a while.

**Comment by alimantu** [comment]
Hello @cobujo, @sretlawd,
Thank you for thoughtful discussion and details, possible location of the problem should help us now to find fix as soon as possible. 👍  Now we are on the way to fix it. Please stay tuned.

**Comment by alimantu** [comment]
Little bit more details.

We've researched the problem and yes, at first it was connected to some changes in poetry, but the main thing is little bit deeper. In our project we are using submodules and the main issue seems to be about init of this submodules during before installation of the package itself, but it's actual only if you're trying to install dxfeed from github sources, because our tar.gz files contain full list of needed files for package compilation and wheels are already compiled and ready-to-use.

In our last release we fixed the incorrect behaviour of our package during installation from PyPI. We've checked it for docker use case too and I can say that Dockerfiles like:
```
FROM python:3.8-slim
RUN apt-get update && apt-get install -y build-essential
RUN pip install dxfeed
```
or
```
FROM python:3.8
RUN pip install dxfeed
```
run smooth, so I hope it would solve your problem with creating working docker container. Meanwhile we'll see if there is another way to fix "installation from github sources using pip" issue aside from downgrading to poetry 1.0.*.

**Comment by alimantu** [comment]
Hi everyone,

One more micro-release here and now you should be able to collect package from github to build your docker image. Please check it out from master or PyPI's last version.

Previous Dockerfiles are still actual + with current master you'll be able to use something like:
```
FROM python:3.8
RUN pip install git+https://github.com/dxFeed/dxfeed-python-api.git
```

Thanks everyone for helpful comments here. 🤗
