### ISSUE TITLE
Update dev dependencies to pandas ^1.0.0

### ISSUE THREAD

**Issue by tdudz** [dxFeed/dxfeed-python-api#36]
Current version is `^0.25.1` but `pandas` latest is `1.3.1`. the `pip` dependency resolver will at most resolve to `0.25.3` due to the versioning semantics involved with `^`. assuming no breaking changes, could we update the `pyproject.toml` to support `pandas == ^1.0.0` ?

**Comment by alimantu** [comment]
Hi @tdudz!

This improvement has been introduced in new release as well 🙂
