### ISSUE TITLE
Cannot pip install dxfeed in Docker container on Apple m1 silicon (arm64)

### ISSUE THREAD

**Issue by 10010111** [dxFeed/dxfeed-python-api#41]
**Describe the bug**
 - Cannot pip install dxfeed in Docker container on Apple m1 silicon (arm64).

**To Reproduce**
Create file named "Dockerfile" with the following content:
----------------------------------
FROM python:3.9

RUN apt-get update
RUN apt-get -y install gcc

RUN pip install --upgrade pip
RUN pip install dxfeed
----------------------------------
Open terminal and go the directory containing Dockerfile and run command "docker build ."

Build process fails to build image on MacMini with Apple m1 silicon (arm64). 

**Behavior**
 - Seems to be an issue with the architecture. Fails with the following message:
gcc -pthread -shared /tmp/pip-install-4uo5lcjy/dxfeed_ef105c2da306413eb6e3bdfb4999afba/build/temp.linux-aarch64-3.9/dxfeed/core/DXFeedPy.o -L/tmp/pip-install-4uo5lcjy/dxfeed_ef105c2da306413eb6e3bdfb4999afba/dxfeed/core -L/usr/local/lib -Wl,--enable-new-dtags,-R$ORIGIN -lDXFeed_64 -o /tmp/pip-install-4uo5lcjy/dxfeed_ef105c2da306413eb6e3bdfb4999afba/build/lib.linux-aarch64-3.9/dxfeed/core/DXFeedPy.cpython-39-aarch64-linux-gnu.so
#8 11.67   /usr/bin/ld: skipping incompatible /tmp/pip-install-4uo5lcjy/dxfeed_ef105c2da306413eb6e3bdfb4999afba/dxfeed/core/libDXFeed_64.so when searching for -lDXFeed_64

DXFeed_64.so seems to be compiled for x86_64 which is what I think is causing /usr/bin/ld to fail on Apple m1 silicon (arm64).

**Expected behavior**
 - Expected to build python:3.9 image with dxfeed installed.

**Environment:**
 - OS: macOS Big Sur Version 11.6
 - Python version: Official python:3.9 docker image from Docker Hub
 - Package version: dxfeed==0.5.3

**Comment by alimantu** [comment]
Hi @10010111,

We finally found some ways to get Apple Silicon M1, so we're going to research this problem a bit deeper on the upcoming week. We are still not quite sure how deep the root of the problem is, so mb we'll be forced to change the architecture of the core C library and in this case it will take us quite a long time, but let's see. 🤷‍♂️ I'll post an update as soon as we'll have estimates of the necessary changes severeness. 🙂

**Comment by 10010111** [comment]
Hi @alimantu,

Again thank you very much for looking into this problem and for the update. Looking forward to the next update! 😃

**Comment by alimantu** [comment]
Hi @10010111,

We have double checked all available options and seems that it would be hardly possible to resolve this issue now if we are talking about solution, we can provide our partners with. The thing here is that this is probably possible, but the result would be kinda one-time solution with lots of trade-offs 🙁, that can seriously impact user experience of you as one of our valuable users. 

The most critical thing here is .NET availability on Apple Silicon processors and progress about it could be tracked via [this board](https://github.com/orgs/dotnet/projects/18). After its resolution we'll be able to make another one approach to this problem's resolution. I'm hoping, that it would be resolved quite soon ane we'll back to you with good news. 🙂

**Comment by tdudz** [comment]
hi @alimantu, have there been any updates with regards to this issue? would love to be able to run dxfeed natively on arm64 mac M1. thanks!

**Comment by tdudz** [comment]
hi @alimantu 

wondering if there is any movement on this issue, as we are a paying user of dxfeed and have been for the last 2 years

**Comment by stdcion** [comment]
HI @tdudz !

Apologies for the late reply, we plan to implement support for Apple Silicon in our new dxfeed-python-api.

We also announce a "feature freeze" for this API as a new version of dxfeed-python-api (ETA Q4 2023) is under development. The new version will have extended functionality (IPF, TimeSeriesEventModel, IndexedEventModel, OrderBook, Apple Silicon architecture support) and a more user-friendly interface (like our [dxFeed Java API](https://docs.dxfeed.com/dxfeed/api/overview-summary.html)).
