### ISSUE TITLE
examples in documentation needs some "sleep" time to actually receive data

### ISSUE THREAD

**Issue by Hoernchen** [dxFeed/dxfeed-python-api#43]
Running the example high level connect/sub/disconnect code (reduced to just the candle data) from the docs quits really fast - apparently too fast, unless there is a sleep() or some other delay between candle_sub.add_symbols() and candle_handler.get_dataframe() the latter will instantly return without any data, and the example code will basically quit without doing anything.

**Comment by stdcion** [comment]
HI @Hoernchen!
Apologies for the late reply, we agree with your statement, and plan to implement new mechanics of receiving data (based on callbacks) in the new API under development.

We also announce a "feature freeze" for this API as a new version of dxfeed-python-api (ETA Q4 2023) is under development. The new version will have extended functionality (IPF, TimeSeriesEventModel, IndexedEventModel, OrderBook, Apple Silicon architecture support) and a more user-friendly interface (like our [dxFeed Java API](https://docs.dxfeed.com/dxfeed/api/overview-summary.html)).
