### ISSUE TITLE
RuntimeError: In underlying C-API library error 43 occurred!

### ISSUE THREAD

**Issue by joncchen** [dxFeed/dxfeed-python-api#44]
Attempts to connect using low level API with dxf_create_connection_auth_bearer('url', 'auth_token') returns a runtime error.

File "dxfeed/core/DXFeedPy.pyx", line 192, in dxfeed.core.DXFeedPy.dxf_create_connection_auth_bearer
RuntimeError: In underlying C-API library error 43 occurred!

**Environment:**
 - OS: [MacOS Monterrey]
 - Python version: [e.g. 3.9.16]
 - Package version: [e.g. 0.5.3]

**Comment by unpfhor** [comment]
I encountered this same issue just now, after spending the last few days getting everything building + running on an arm64 mac. I was worried that it was a side effect of my changes, so I'm somewhat relieved to hear it's a pre-existing bug.

The error code in question (43) is `dx_sec_host_not_found` in the C API, which on macos is mapped to `EAI_NONAME`. The only place `EAI_NONAME` would be triggered is `dx_getaddrinfo`, which is indeed called during `dx_create_connection_auth_bearer`:

`dx_create_connection_auth_bearer`
  |-> `dxf_create_connection_auth_custom`
    |-> `dxf_create_connection_impl`
      |-> `dx_bind_to_address`
        |-> `dx_resolve_address`
          |-> `dx_getaddrinfo`

So something is causing the name resolution to fail. Either the host/service is being mangled between the Python and C layers, or there's some deeper underlying DNS issue, but in my case the hostname I'm using resolves correctly in any other context outside of the dxfeed API.

**Comment by pressplay21** [comment]
same issue using the standard socket endpoint format

\dxfeed\core\DXFeedPy.pyx:192, in dxfeed.core.DXFeedPy.dxf_create_connection_auth_bearer()

RuntimeError: In underlying C-API library error 56 occurred!

**Comment by stdcion** [comment]
Hi @pressplay21!

It looks like you are trying to connect to an endpoint, which is a websocket. 
Unfortunately, this API can only work with the binary QTP protocol.

We also announce a "feature freeze" for this API as a new version of dxfeed-python-api (ETA Q4 2023) is under development. The new version will have extended functionality (IPF, TimeSeriesEventModel, IndexedEventModel, OrderBook, Apple Silicon architecture support) and a more user-friendly interface (like our [dxFeed Java API](https://docs.dxfeed.com/dxfeed/api/overview-summary.html)).
