### ISSUE TITLE
How do you authenticate with dxfeed endpoints?

### ISSUE THREAD

**Issue by pressplay21** [dxFeed/dxfeed-python-api#45]
How can I authenticate with dxfeed endpoints? Please provide some guidance. 

from dxfeed.core import DXFeedPy as dxc
from dxfeed.core.utils.handler import DefaultHandler

streamer_url = 'tasty-live.dxfeed.com:7301'
dx_conn = dxc.dxf_create_connection_auth_bearer(streamer_url,streamer_token)
dx_sub = dxc.dxf_create_subscription(dx_conn,"Trade")
dx_sub.set_event_handler(DefaultHandler())
dxc.dxf_add_symbols(dx_sub,["SPX"])

dx_sub.get_event_handler().get_list()
[] #I'm getting an empty list.

**Comment by stdcion** [comment]
Hi @pressplay21 

Unfortunately, this API can only work with the binary QTP protocol. The endpoint you are trying to connect to uses the websocket protocol, which is not supported in this API.

We also announce a "feature freeze" for this API as a new version of dxfeed-python-api (ETA Q4 2023) is under development. The new version will have extended functionality (IPF, TimeSeriesEventModel, IndexedEventModel, OrderBook, Apple Silicon architecture support) and a more user-friendly interface (like our [dxFeed Java API](https://docs.dxfeed.com/dxfeed/api/overview-summary.html)).
